### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by LukinoCZ** [CapMousse/Graph.js#3]
Can you please add any simple example? Is fine to see how to expand it but is missing simple working example, all showed graphs are images only.

**Comment by CapMousse** [comment]
Yup, I will add some examples :)

**Comment by lmolent** [comment]
+1 :)

**Comment by geotheory** [comment]
Bit confused why you'd publish this really nice little project and blog it on Medium, but not make a single example?

**Comment by CapMousse** [comment]
@geotheory because sometime professional work take to much time to work on personal projects !

But hey, it's here ! https://graph.jeremy.sh/

**Comment by sotisoti** [comment]
https://graph.jeremy.sh/ is down..
